### ISSUE TITLE
New Controller Not Recognized

### ISSUE THREAD

**Issue by phil-kt** [zguillez/generator-base-angularjs#2]
I have a new basic controller defined in controllers folder, new.js 

```
define([], function() {
  'use strict';

  function newController($scope, $location, $http, $route, $routeParams) {
    console.log($routeParams.page);
  }

  newController.$inject = ['$scope', '$http', '$location', '$route', '$routeParams'];
  return newController;
});
```

which I've thus included in controllers.js

```
define(['controllers/new'], function(newController) {
  'use strict';
  window.app.controller('newController', newController);
});
```

and have a route to it

```
when('/:page', {
        templateUrl: 'templates/new.html',
        controller: 'newController'
      }).
```

However, when I hit this route, here's what my console spits out:

```
angular.min.js:107 Error: [ng:areq] http://errors.angularjs.org/1.4.9/ng/areq?p0=newController&p1=not%20aNaNunction%2C%20got%20undefined
    at Error (native)
    at http://localhost:9000/lib/angular.min.js:6:416
    at rb (http://localhost:9000/lib/angular.min.js:22:130)
    at Qa (http://localhost:9000/lib/angular.min.js:22:217)
    at http://localhost:9000/lib/angular.min.js:80:210
    at A.link (http://localhost:9000/lib/angular-route.min.js:7:268)
    at ca (http://localhost:9000/lib/angular.min.js:73:279)
    at I (http://localhost:9000/lib/angular.min.js:62:174)
    at g (http://localhost:9000/lib/angular.min.js:55:97)
    at http://localhost:9000/lib/angular.min.js:54:239
```

Which links me to the angular error page saying: 

```
Error: ng:areq
Bad Argument
Argument 'newController' is not a
```

Which obviously isn't that informative. What am I doing wrong?

**Comment by zguillez** [comment]
I check the generator and I create a new controller without any error..
¿You make changes on the index or main.js?

I make a new controller on the base code and I zip it. You can download it and check the code:
[new-controller-test.zip](https://github.com/zguillez/generator-base-angularjs/files/169901/new-controller-test.zip)
